version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile    # Mount your Caddyfile
      - caddy_data:/data                    # SSL certificates, etc.
      - caddy_config:/config
    networks:
      - caddy_network
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_network:
    driver: bridge





# docker network create caddy_network
