---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest  # Apache web server image
        ports:
        - containerPort: 80  # Apache listens on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80            # Apache listens on port 80 in the container
      targetPort: 80       # Maps the container port to the service
      nodePort: 30200      # The NodePort you want to use
