version: "2"

services:
  server:
    image: docker.io/gitea/gitea:1.23.4-rootless
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000" #For web access
      - "2222:2222" #For ssh access
    depends_on:
      - db

  db:
    image: docker.io/library/mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql

#   caddy:
#     image: caddy:latest
#     container_name: caddy
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile    # Mount your Caddyfile
#       - caddy_data:/data                    # SSL certificates, etc.
#       - caddy_config:/config
#     # networks:
#     #   - caddy_network
#     restart: unless-stopped

# volumes:
#   caddy_data:
#   caddy_config: