version: '3.8'

services:
  traefik:
    image: traefik:v3.1.6
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"                     # Enable Traefik's dashboard
      - "--api.insecure=true"  # Optional: Only for local testing. Use secure access in production.
      - "--providers.docker=true"                  # Enable Docker provider to discover containers
      - "--entrypoints.web.address=:80"            # Define HTTP entrypoint
      - "--entrypoints.websecure.address=:443"     # Define HTTPS entrypoint
      - "--certificatesresolvers.mytls.acme.tlschallenge=true"  # Enable TLS challenge for certs
      - "--certificatesresolvers.mytls.acme.email=incriszluv@gmail.com"  # Your email for ACME
      - "--certificatesresolvers.mytls.acme.storage=/letsencrypt/acme.json"  # Store certs

    ports:
      - "80:80"      # Expose HTTP port
      - "443:443"    # Expose HTTPS port
      - "8080:8080"  # Expose dashboard on port 8080

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Docker socket for Traefik to access containers
      - "./letsencrypt:/letsencrypt"                   # Persist ACME certs

    networks:
      - coolify

  nginx:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.rule=Host(`nginx.cyfamod.com`)"
      # - "traefik.http.routers.apache.entrypoints=websecure"
      # - "traefik.http.routers.apache.tls.certresolver=mytls"

networks:
  coolify:
    external: true



# docker network create traefik_network
