version: '3.8'

services:
  traefik:
    image: traefik:v3.1.6
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"                     # Enable Traefik's dashboard
      - "--api.insecure=true"  # Optional: Only for local testing. Use secure access in production.
      - "--providers.docker=true"                  # Enable Docker provider to discover containers
      - "--entrypoints.web.address=:80"            # Define HTTP entrypoint
      - "--entrypoints.websecure.address=:443"     # Define HTTPS entrypoint
      - "--certificatesresolvers.mytls.acme.tlschallenge=true"  # Enable TLS challenge for certs
      - "--certificatesresolvers.mytls.acme.email=incriszluv@gmail.com"  # Your email for ACME
      - "--certificatesresolvers.mytls.acme.storage=/letsencrypt/acme.json"  # Store certs and ensures renewal
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"  # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"  # Ensure redirection uses HTTPS

    ports:
      - "80:80"      # Expose HTTP port
      - "443:443"    # Expose HTTPS port
      - "8080:8080"  # Expose dashboard on port 8080

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Docker socket for Traefik to access containers
      - "./letsencrypt:/letsencrypt"                   # Persist ACME certs

    networks:
      - traefik_network

  apache:
    image: httpd:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.entrypoints=websecure"    # Ensure traffic is served over HTTPS
      - "traefik.http.routers.apache.rule=Host(`apache.cyfamod.com`)"  # Domain for the Apache service
      - "traefik.http.routers.nginx.tls=true"                      # Enable TLS for this service
      - "traefik.http.routers.apache.tls.certresolver=mytls"   # Use ACME resolver for SSL certs
    networks:
      - traefik_network
  nginx:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"    # Ensure traffic is served over HTTPS
      - "traefik.http.routers.nginx.rule=Host(`open.cyfamod.com`)"  # Domain for the nginx service
      - "traefik.http.routers.nginx.tls=true"                      # Enable TLS for this service
      - "traefik.http.routers.nginx.tls.certresolver=mytls"   # Use ACME resolver for SSL certs
    networks:
      - traefik_network
networks:
  traefik_network:
    external: true
