version: '3'
services:
  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 1ncrease
      MYSQL_DATABASE: mebany
      MYSQL_USER: incrisz
      MYSQL_PASSWORD: 1ncrease
    ports:
      - "3306:3306"
  
  phpmyadmin:
    container_name: control
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1ncrease
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
