version: '3.8'

services:
  traefik:
    image: traefik:v3.1.6
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"                     # Enable Traefik's dashboard
      - "--api.insecure=true"                      # Optional: Only for local testing. Use secure access in production.
      - "--providers.docker=true"                  # Enable Docker provider to discover containers
      - "--entrypoints.web.address=:80"            # Define HTTP entrypoint
      - "--entrypoints.websecure.address=:443"     # Define HTTPS entrypoint
      - "--certificatesresolvers.mytls.acme.tlschallenge=true"  # Enable TLS challenge for certs
      - "--certificatesresolvers.mytls.acme.email=incriszluv@gmail.com"  # Your email for ACME
      - "--certificatesresolvers.mytls.acme.storage=/letsencrypt/acme.json"  # Store certs
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"  # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"  # Ensure redirection uses HTTPS

    ports:
      - "80:80"      # Expose HTTP port
      - "443:443"    # Expose HTTPS port
      - "8080:8080"  # Expose dashboard on port 8080

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Docker socket for Traefik to access containers
      - "./letsencrypt:/letsencrypt"                   # Persist ACME certs

    networks:
      - traefik_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1ncrease
      MYSQL_DATABASE: mebany
      MYSQL_USER: incrisz
      MYSQL_PASSWORD: 1ncrease
    networks:
      - traefik_network  # Add the database to the traefik network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - traefik_network  # Add phpMyAdmin to the traefik network
    labels:
      - "traefik.enable=true"  # Enable Traefik for phpMyAdmin
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.cyfamod.com`)"  # Rule for accessing phpMyAdmin
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"  # Use secure entrypoint
      - "traefik.http.routers.phpmyadmin.tls=true"  # Enable TLS
      - "traefik.http.routers.phpmyadmin.tls.certresolver=mytls"  # Use ACME resolver for SSL certs
      - "traefik.http.services.phpmyadmin-service.loadbalancer.server.port=80"  # Point to phpMyAdmin's internal port

    environment:
      PMA_HOST: db  # Reference the database service
      MYSQL_ROOT_PASSWORD: 1ncrease  # MySQL root password

networks:
  traefik_network:
    external: true
