global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
  - "rules/node_exporter_alerts.yml"
  - "rules/blackbox_exporter_alerts.yml"
  - "rules/test_alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['199.192.27.235:9100']
  - job_name: 'alert'
    static_configs:
      - targets: ['localhost:9093']
  - job_name: 'dora_metrics'
    static_configs:
      - targets: ['localhost:8001']
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://ipala.shop
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
  - job_name: 'blackbox_ssl'
    metrics_path: /probe
    params:
      module: [http_ssl]
    static_configs:
      - targets:
        - https://ipala.shop
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
