apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80            # The port your service will expose inside the cluster
      targetPort: 80       # The port your container listens on
      nodePort: 30008      # Specify a port in the range 30000-32767 or let Kubernetes choose one
