version: '3'

services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptimekuma
    ports:
      - 3001:3001
    volumes:
      - uptimekuma-data:/app/data
    restart: unless-stopped
  # caddy:
  #   image: caddy:latest
  #   container_name: caddy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile    # Mount your Caddyfile
  #     - caddy_data:/data                    # SSL certificates, etc.
  #     - caddy_config:/config
  #   # networks:
  #   #   - caddy_network
  #   restart: unless-stopped

volumes:
  uptimekuma-data:
    driver: local
  # caddy_data:
  # caddy_config:
  