apiVersion: v1                     # Specifies the API version of the Kubernetes object.
kind: Service                      # Defines the kind of object, in this case, a Service.
metadata:                          # Metadata for the service.
  name: apache-service              # Name of the service to be created.
spec:                               # Specification for the service.
  selector:                        # Selector to identify which pods the service will target.
    app: apache                     # Label selector to match pods with the label 'app: apache'.
  ports:                           # List of ports exposed by the service.
    - protocol: TCP                 # Protocol used by the service (TCP in this case).
      port: 80                     # The port exposed by the service (accessible to external traffic).
      targetPort: 80                # The port on the container that the service will forward traffic to.
  type: NodePort                # Type of service. LoadBalancer creates an external load balancer.
                                   # If LoadBalancer is not supported, use NodePort.
